name: Gomi reminder

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install dependecies
      run: bundle install
    - name: run script
      env:
        CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
      run: |
        ruby lib/moenai_gomi.rb